# Generated by Django 3.1.1 on 2020-09-10 12:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0002_auto_20200909_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='means',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Определения'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='words',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Слова'),
        ),
        migrations.AlterField(
            model_name='inputtest',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_test', to='shool.lesson', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='shool.lesson', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='testchoice',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='shool.test', verbose_name='Этап'),
        ),
    ]
