# Generated by Django 3.1.1 on 2020-09-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0003_auto_20200910_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='inputtest',
            options={'verbose_name': 'Тест-ввод', 'verbose_name_plural': 'Тесты-ввод'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testchoice',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='testchoice',
            name='image',
            field=models.ImageField(blank=True, upload_to='tests/'),
        ),
        migrations.AlterField(
            model_name='inputtest',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_test', to='shool.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='shool.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='testchoice',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='testchoice',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='shool.test', verbose_name='Тест'),
        ),
    ]
