# Generated by Django 3.1.1 on 2020-09-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0004_auto_20200910_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='depences_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зависит от ID'),
        ),
        migrations.AlterField(
            model_name='testchoice',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='shool.test', verbose_name='Тест'),
        ),
    ]
