# Generated by Django 3.1.1 on 2020-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0007_auto_20200916_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='bg_image',
            field=models.ImageField(null=True, upload_to='course', verbose_name='Картинка для бекграунда'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_color',
            field=models.ImageField(null=True, upload_to='course', verbose_name='Иконка цветная'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_white',
            field=models.ImageField(null=True, upload_to='course', verbose_name='Иконка белая'),
        ),
    ]
