# Generated by Django 3.1.1 on 2020-09-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0008_auto_20200917_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='depence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shool.course'),
        ),
    ]
