# Generated by Django 3.1.1 on 2020-09-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0009_course_depence'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points_to_balance',
            field=models.IntegerField(null=True),
        ),
    ]
