# Generated by Django 3.1.1 on 2020-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0010_course_points_to_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(null=True, upload_to='course', verbose_name='Бекграунд')),
                ('top', models.ImageField(null=True, upload_to='course', verbose_name='Маленькая картинка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
