# Generated by Django 3.1.1 on 2020-10-05 17:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0011_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='icon_white',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='course',
            name='icon_color',
        ),
        migrations.AddField(
            model_name='course',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
