# Generated by Django 3.1.1 on 2020-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0012_auto_20201005_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('crerated_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Форма обратной сваязи',
                'verbose_name_plural': 'Формы обратной сваязи',
            },
        ),
    ]
