# Generated by Django 3.1.1 on 2020-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzleimage',
            options={'verbose_name': 'Картинка пазла', 'verbose_name_plural': 'Картинка для пазлов'},
        ),
        migrations.RemoveField(
            model_name='puzzleimage',
            name='image',
        ),
        migrations.AddField(
            model_name='puzzleimage',
            name='video',
            field=models.FileField(null=True, upload_to='puzzleimage/', verbose_name='Картинка'),
        ),
    ]
