# Generated by Django 3.1.1 on 2020-09-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0002_auto_20200909_1503'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_course', to='shool.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='done_course',
            field=models.ManyToManyField(blank=True, related_name='done_course', to='shool.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='done_lessons',
            field=models.ManyToManyField(blank=True, to='shool.Lesson'),
        ),
    ]
