# Generated by Django 3.1.1 on 2020-09-12 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0005_auto_20200912_1348'),
        ('user', '0003_user_current_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_course',
        ),
        migrations.AddField(
            model_name='user',
            name='current_course',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_course', to='shool.Course'),
        ),
        migrations.CreateModel(
            name='CourseStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shool.course', verbose_name='Курс')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
        ),
    ]
