# Generated by Django 3.1.1 on 2020-09-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200912_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_lesson',
        ),
        migrations.RemoveField(
            model_name='user',
            name='done_course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='done_lessons',
        ),
        migrations.DeleteModel(
            name='CourseStart',
        ),
    ]
