# Generated by Django 3.1.1 on 2020-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200914_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achives', verbose_name='Фото')),
                ('rules', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='achives',
            field=models.ManyToManyField(blank=True, to='user.Achive'),
        ),
    ]
