# Generated by Django 3.1.1 on 2020-09-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0007_auto_20200916_1033'),
        ('user', '0006_auto_20200915_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avaiable_courses',
            field=models.ManyToManyField(blank=True, default=1, to='shool.Course', verbose_name='Доступные курсы'),
        ),
    ]
