# Generated by Django 3.1.1 on 2020-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0007_auto_20200916_1033'),
        ('user', '0007_user_avaiable_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finished_courses',
            field=models.ManyToManyField(blank=True, related_name='finished_courses', to='shool.Course', verbose_name='Завершенные курсы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avaiable_courses',
            field=models.ManyToManyField(blank=True, related_name='avaiable_courses', to='shool.Course', verbose_name='Доступные курсы'),
        ),
    ]
