# Generated by Django 3.1.1 on 2020-09-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shool', '0008_auto_20200917_1251'),
        ('user', '0008_auto_20200917_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress_courses',
            field=models.ManyToManyField(blank=True, related_name='progress_courses', to='shool.Course', verbose_name='В процессе курсы'),
        ),
    ]
