# Generated by Django 3.1.1 on 2020-09-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_progress_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Иван', max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
