# Generated by Django 3.1.1 on 2020-09-21 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='achives',
        ),
        migrations.AddField(
            model_name='achive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achive',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achives', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='achive',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='achive',
            name='rules',
            field=models.TextField(blank=True, null=True, verbose_name='Иконка'),
        ),
    ]
