# Generated by Django 3.1.1 on 2020-09-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200921_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='achive',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='achive',
            name='rules',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
    ]
