# Generated by Django 3.1.1 on 2020-09-21 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200921_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achive',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='achive',
            name='user',
        ),
        migrations.CreateModel(
            name='EarnedAchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('achives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.achive')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achives_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
