# Generated by Django 3.1.1 on 2020-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200921_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Промокод'),
        ),
    ]
