# Generated by Django 3.1.1 on 2020-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry_time',
            field=models.DateField(blank=True, null=True, verbose_name='Истечение аккаунта'),
        ),
    ]
